[tool.poetry]
name = "cl"
version = "0.1.0"
description = ""
authors = ["aaaaninja <aaaaninja@aaaa.ninja>"]

[tool.poetry.dependencies]
python = "^3.8"
cloudia = "^0.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
